//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.06.18 at 07:07:29 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webis.de/feedreader/model/atom", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package jaxb;
